// react-cli/src/App.jsx
import React, { Suspense, lazy } from 'react'
import { Link, Routes, Route } from 'react-router-dom'
import { ConfigProvider, Button } from 'antd'
// import Home from './pages/Home'
// import About from './pages/About'

const Home = lazy(() => import(/* webpackChunkName: 'home' */ './pages/Home'))
const About = lazy(() =>
  import(/* webpackChunkName: 'about' */ './pages/About')
)

function App() {
  return (
    <div>
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: '#00b96b',
          },
        }}
      >
        <h1>App</h1>
        <Button type="primary"> 按钮</Button>
        <ul>
          <li>
            <Link to="/home">Home</Link>
          </li>
          <li>
            <Link to="/about">About</Link>
          </li>
        </ul>

        <Suspense fallback={<div>loading...</div>}>
          <Routes>
            <Route path="/home" element={<Home />} />
            <Route path="/about" element={<About />} />
          </Routes>
        </Suspense>
      </ConfigProvider>
    </div>
  )
}

export default App

// vue-cli/src/App.vue
<template>
  <h1 class="title">hello world</h1>
  <el-button type="primary">按钮</el-button>
  <ul>
    <li><router-link to="/home">去Home</router-link></li>
    <li><router-link to="/about">去About</router-link></li>
  </ul>

  <router-view />
</template>

<script>
export default {
  name: 'App',
}
</script>

<style>
.title {
  color: blueviolet;
}
</style>
